<a href="https://colab.research.google.com/github/davidrpugh/machine-learning-for-tabular-data/blob/main/notebooks/lecture-4-part-1c.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [50]:
import pathlib

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn import compose, datasets, linear_model, metrics, model_selection
from sklearn import preprocessing, pipeline

# Preprocessing with Scikit-Learn

In [51]:
features, targets = datasets.load_diabetes(
    return_X_y=True,
    as_frame=True,
    scaled=False
)

In [52]:
features.head()

    age  sex   bmi     bp     s1     s2    s3   s4      s5    s6
0  59.0  2.0  32.1  101.0  157.0   93.2  38.0  4.0  4.8598  87.0
1  48.0  1.0  21.6   87.0  183.0  103.2  70.0  3.0  3.8918  69.0
2  72.0  2.0  30.5   93.0  156.0   93.6  41.0  4.0  4.6728  85.0
3  24.0  1.0  25.3   84.0  198.0  131.4  40.0  5.0  4.8903  89.0
4  50.0  1.0  23.0  101.0  192.0  125.4  52.0  4.0  4.2905  80.0

In [53]:
features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     442 non-null    float64
 1   sex     442 non-null    float64
 2   bmi     442 non-null    float64
 3   bp      442 non-null    float64
 4   s1      442 non-null    float64
 5   s2      442 non-null    float64
 6   s3      442 non-null    float64
 7   s4      442 non-null    float64
 8   s5      442 non-null    float64
 9   s6      442 non-null    float64
dtypes: float64(10)
memory usage: 34.7 KB

In [54]:
targets.describe()

count    442.000000
mean     152.133484
std       77.093005
min       25.000000
25%       87.000000
50%      140.500000
75%      211.500000
max      346.000000
Name: target, dtype: float64

## Train-test split

In [55]:
prng = np.random.RandomState(42)

train_features, test_features, train_targets, test_targets = (
    model_selection.train_test_split(
        features,
        targets,
        random_state=prng,
        test_size=0.2
    )
)

## Feature Preprocessing

In [56]:
feature_encoding = compose.make_column_transformer(
    (
        preprocessing.OneHotEncoder(
            drop="first",
            dtype=np.uint8,
            sparse_output=False,
        ),
        ["sex"]
    ),
    force_int_remainder_cols=False,
    remainder="passthrough",
    verbose=False,
    verbose_feature_names_out=False
)


feature_scaling = compose.make_column_transformer(
    (
        preprocessing.StandardScaler(),
        ["age", "bmi", "bp", "s1", "s2", "s3", "s4", "s5", "s6"]
    ),
    force_int_remainder_cols=False,
    remainder="passthrough",
    verbose=False,
    verbose_feature_names_out=False
)

feature_preprocessing = pipeline.make_pipeline(
    feature_encoding,
    feature_scaling,
).set_output(transform="pandas")

In [57]:
feature_preprocessing

Pipeline(steps=[('columntransformer-1',
                 ColumnTransformer(force_int_remainder_cols=False,
                                   remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(drop='first',
                                                                dtype=<class 'numpy.uint8'>,
                                                                sparse_output=False),
                                                  ['sex'])],
                                   verbose_feature_names_out=False)),
                ('columntransformer-2',
                 ColumnTransformer(force_int_remainder_cols=False,
                                   remainder='passthrough',
                                   transformers=[('standardscaler',
                                                  StandardScaler(),
                                                  ['age', 'bmi', 'bp', 's1',
                                                   's2', 's3', 's4', 's5',
                                                   's6'])],
                                   verbose_feature_names_out=False))])

In [58]:
feature_preprocessing.fit_transform(train_features)

,age,bmi,bp,s1,s2,s3,s4,s5,s6,sex_2.0
17,1.498365,0.219902,1.138874,0.728473,1.055893,-0.824451,0.711038,0.547482,-0.061449,1
66,-0.228858,-0.419366,-0.710591,-0.424929,0.272425,-1.529791,1.484286,-0.019757,0.367236,1
137,0.085182,1.018987,1.992473,-0.309589,-0.326699,-0.119111,-0.062210,0.331237,-0.318660,0
245,-0.621409,-0.784662,-0.639458,-1.174640,-1.215508,0.664600,-0.835458,-1.069682,-2.719299,0
31,-0.542899,-1.423930,-1.706457,-0.799784,-1.110167,1.291569,-1.608706,-0.802859,-0.918820,0
...,...,...,...,...,...,...,...,...,...,...
106,-2.113102,-1.652240,-0.923991,-0.943960,-0.715141,0.194374,-0.835458,-1.270659,-1.776191,0
270,0.085182,0.608029,1.707940,-0.770949,-0.978492,0.351116,-0.835458,0.155454,0.281499,1
348,0.634754,-0.465028,-0.141525,-0.078908,-0.603217,1.683425,-0.835458,-0.253752,-0.061449,0
435,-0.307368,-0.533521,-0.852858,-0.338424,0.114414,-0.354224,-0.062210,-0.830724,-0.833083,0
102,-2.034592,0.562367,-0.354925,0.786143,0.542359,1.213198,-0.835458,-0.133128,-0.061449,0

In [59]:
target_preprocessor = preprocessing.FunctionTransformer(
    func=np.log,
    inverse_func=np.exp
)

In [60]:
target_preprocessor

FunctionTransformer(func=<ufunc 'log'>, inverse_func=<ufunc 'exp'>)

In [61]:
target_preprocessor.fit_transform(train_targets)

17     4.969813
66     5.010635
137    5.634790
245    4.828314
31     4.077537
         ...
106    4.897840
270    5.308268
348    4.997212
435    4.158883
102    5.710427
Name: target, Length: 353, dtype: float64

## Model training

### Using LinearRegression

In [62]:
_regressor = compose.TransformedTargetRegressor(
    regressor=linear_model.LinearRegression(),
    transformer=target_preprocessor
)

linear_regression_pipeline = pipeline.make_pipeline(
    feature_preprocessing,
    _regressor
)

In [63]:
%%timeit
_ = linear_regression_pipeline.fit(train_features, train_targets)

14.6 ms ± 2.01 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [64]:
_ = linear_regression_pipeline.fit(train_features, train_targets)

In [65]:
train_predictions = linear_regression_pipeline.predict(train_features)
train_rmse = metrics.root_mean_squared_error(
    train_targets,
    train_predictions,
)
print(f"Training rmse: {train_rmse}")

Training rmse: 54.62875166966212

In [66]:
test_predictions = linear_regression_pipeline.predict(test_features)
test_rmse = metrics.root_mean_squared_error(
    test_targets,
    test_predictions,
)
print(f"Testing rmse: {test_rmse}")

Testing rmse: 55.1204825979791

### Using SGDRegressor

In [67]:
_regressor = compose.TransformedTargetRegressor(
    regressor=linear_model.SGDRegressor(),
    transformer=target_preprocessor
)

sgd_regressor_pipeline = pipeline.make_pipeline(
    feature_preprocessing,
    _regressor
)

In [68]:
sgd_regressor_pipeline

Pipeline(steps=[('pipeline',
                 Pipeline(steps=[('columntransformer-1',
                                  ColumnTransformer(force_int_remainder_cols=False,
                                                    remainder='passthrough',
                                                    transformers=[('onehotencoder',
                                                                   OneHotEncoder(drop='first',
                                                                                 dtype=<class 'numpy.uint8'>,
                                                                                 sparse_output=False),
                                                                   ['sex'])],
                                                    verbose_feature_names_out=False)),
                                 ('columntransformer-2',
                                  ColumnTransformer(force_int_remainder_cols=False,
                                                    remainder='passthrough',
                                                    transformers=[('standardscaler',
                                                                   StandardScaler(),
                                                                   ['age',
                                                                    'bmi', 'bp',
                                                                    's1', 's2',
                                                                    's3', 's4',
                                                                    's5',
                                                                    's6'])],
                                                    verbose_feature_names_out=False))])),
                ('transformedtargetregressor',
                 TransformedTargetRegressor(regressor=SGDRegressor(),
                                            transformer=FunctionTransformer(func=<ufunc 'log'>,
                                                                            inverse_func=<ufunc 'exp'>)))])

In [69]:
%%timeit
_ = sgd_regressor_pipeline.fit(train_features, train_targets)

15.4 ms ± 2 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [70]:
_ = sgd_regressor_pipeline.fit(train_features, train_targets)

In [71]:
train_predictions = sgd_regressor_pipeline.predict(train_features)
train_rmse = metrics.root_mean_squared_error(
    train_targets,
    train_predictions,
)
print(f"Training rmse: {train_rmse}")

Training rmse: 57.4715492926135

In [72]:
test_predictions = sgd_regressor_pipeline.predict(test_features)
test_rmse = metrics.root_mean_squared_error(
    test_targets,
    test_predictions,
)
print(f"Testing rmse: {test_rmse}")

Testing rmse: 54.75737587056216

### Exercise

Compare the training loss and the testing loss. Is the model underfitting or overfitting? How can you tell?